name: goreleaser

on:
  pull_request:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
    calculate-version:
      name: Calculate Version
      runs-on: ubuntu-latest
      outputs:
        semVer: ${{ steps.gitversion.outputs.semVer }}
        AssemblySemFileVer: ${{ steps.gitversion.outputs.AssemblySemFileVer }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with: 
            fetch-depth: 0 # only need to get GitVersion file
        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0.9.11
          with:
            versionSpec: '5.x'
        - name: Use GitVersion
          uses: gittools/actions/gitversion/execute@v0.9.11
          id: gitversion
    build_release:
      name: Create Release
      runs-on: windows-latest
      needs: calculate-version
      env:
        SEMVER: ${{ needs.calculate-version.outputs.semVer }}
        ASSEMBLYSEMVER: ${{ needs.calculate-version.outputs.AssemblySemFileVer }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Go
          uses: actions/setup-go@v4
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v5
          with:
            # either 'goreleaser' (default) or 'goreleaser-pro'
            distribution: goreleaser
            version: latest
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
